### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by boymag** [smallyard/tianqi#1]
[root@localhost node]# /usr/local/src/node-v8.1.2-linux-x86/bin/tianqi 上海
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/src/node-v8.1.2-linux-x86/lib/node_modules/tianqi/src/index.js:35:30)
    at Request.self.callback (/usr/local/src/node-v8.1.2-linux-x86/lib/node_modules/tianqi/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/src/node-v8.1.2-linux-x86/lib/node_modules/tianqi/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/local/src/node-v8.1.2-linux-x86/lib/node_modules/tianqi/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)

**Comment by smallyard** [comment]
Sorry, this project is no longer maintained.

**Comment by smallyard** [comment]
@boymag fix
